#!/usr/bin/env python3
"""
Fetch the Omarchy plugin marketplace registry and produce a pinned source list
for census.py.

The registry lives at the root of HANCORE's marketplace repo. Every source entry
carries a `listingValidatedCommit` — the exact commit the marketplace validated.
The census pins to that commit rather than cloning HEAD, so the audit describes
what was actually listed, is reproducible, and can't be gamed by pushing after
listing.

The registry also carries HANCORE's own `automatedSecurityBaseline`, whose
capability vocabulary covers the *install path*. This script extracts it so the
census can report coverage side by side rather than duplicating it.

Usage:
    python3 fetch_registry.py --out census/
    python3 census.py census/plugins.txt --out census/
"""

import argparse
import json
import sys
import urllib.error
import urllib.request
from collections import Counter
from pathlib import Path

REGISTRY_URL = (
    "https://raw.githubusercontent.com/HANCORE-linux/"
    "omarchy-plugin-marketplace/main/registry.json"
)


def fetch(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": "omaudit-census"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        print(f"fetch_registry: could not read {url}: {exc}", file=sys.stderr)
        raise SystemExit(1)


def extract(registry: dict) -> tuple[list[dict], dict]:
    sources = registry.get("sources") or []
    retired = set(registry.get("retiredPluginIds") or [])

    entries = []
    for src in sources:
        repo = src.get("repo")
        if not repo:
            continue
        plugin_ids = list((src.get("plugins") or {}).keys())
        if plugin_ids and all(pid in retired for pid in plugin_ids):
            continue
        baseline = src.get("automatedSecurityBaseline") or {}
        entries.append({
            "repo": repo,
            "commit": src.get("listingValidatedCommit"),
            "branch": src.get("listingValidatedBranch"),
            "type": src.get("type"),
            "pluginIds": plugin_ids,
            "baselineOutcome": baseline.get("outcome"),
            "baselineCapabilities": baseline.get("capabilities") or [],
            "baselineFindings": baseline.get("findings") or [],
            "hasBaseline": bool(baseline),
        })

    withb = [e for e in entries if e["hasBaseline"]]
    stats = {
        "sources": len(entries),
        "withUpstreamBaseline": len(withb),
        "baselineOutcomes": dict(Counter(
            e["baselineOutcome"] for e in withb if e["baselineOutcome"])),
        "baselineCapabilityFrequency": dict(Counter(
            c for e in withb for c in e["baselineCapabilities"]).most_common()),
        "baselineFindingCount": sum(len(e["baselineFindings"]) for e in withb),
        "sourcesWithAnyBaselineCapability": sum(
            1 for e in withb if e["baselineCapabilities"]),
    }
    return entries, stats


def main() -> int:
    ap = argparse.ArgumentParser(description="Fetch the marketplace registry")
    ap.add_argument("--url", default=REGISTRY_URL)
    ap.add_argument("--out", default="census")
    ap.add_argument("--unpinned", action="store_true",
                    help="emit bare repo URLs instead of repo@commit")
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    print(f"fetching {args.url}")
    registry = fetch(args.url)
    entries, stats = extract(registry)

    lines = ["# generated by fetch_registry.py — repo@commit, pinned to the",
             "# commit the marketplace validated at listing time"]
    for e in entries:
        if e["commit"] and not args.unpinned:
            lines.append(f"{e['repo']}@{e['commit']}")
        else:
            lines.append(e["repo"])

    (out / "plugins.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (out / "registry-entries.json").write_text(json.dumps(entries, indent=2), encoding="utf-8")
    (out / "upstream-baseline.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

    print(f"\n{stats['sources']} sources, "
          f"{stats['withUpstreamBaseline']} with an upstream security baseline")
    print(f"upstream outcomes: {stats['baselineOutcomes']}")
    print(f"upstream findings across the whole registry: "
          f"{stats['baselineFindingCount']}")
    print("\nupstream capability vocabulary (install-path coverage):")
    for cap, n in stats["baselineCapabilityFrequency"].items():
        print(f"  {n:>4}  {cap}")
    print(f"\nwrote {out}/plugins.txt, registry-entries.json, "
          f"upstream-baseline.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
